grid:
  x_min: -5.0
  x_max: 5.0
  nx: 201
  T: 0.5
  nt: 150
  bc: neumann
params:
  nu: 0.001985
  phi: 0.035359
  gamma_T: 0.568862
  eta0: 0.000555
  eta1: 0.029442
  m0_mean: 0.0
  m0_std: 1.0
solver:
  max_iter: 200
  tol: 1.0e-06
  relative_tol: 0.0005
  mix: 0.3
  mix_min: 0.0001
  mix_decay: 0.5
  stagnation_tol: 0.02
  use_dynamic_eta: true
